language: csharp
dist: xenial
sudo: false
dotnet: 2.2.105
os: linux

stages:
  - build
  - test

services:
  - postgresql

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  include:
    - stage: build
      mono: 5.16.0
      before_script:
        - mono .paket/paket.exe restore
        - yarn install
        - dotnet restore build.proj
      script:
        - dotnet fake build
    - stage: test
      script:
        - cd src/Server; dotnet run &
        - cd ../..; sleep 20
        - cd Tests; dotnet run
        - kill %1
        - echo "done"
